---
- name: setting Vagrant for CentOS
  hosts: dev_server
  remote_user: vagrant
  become: yes
  gather_facts: no

  roles:
    - yum_repo
    - yum_install
    - git
    - dotfiles
    - zsh
    - peco
    - tmux
    # - apache
    - nginx
    - mysql
    - vim
    - ruby
    - nodejs
