---
- name: install basic packages
  yum: name={{ item }} state=present
  with_items:
    - curl
    - wget
    - gcc
    - make
    - libselinux-python
    - ruby-devel
    - readline-devel
    - ncurses-devel
    - gdbm-devel
    - openssl-devel
    - libxslt-devel
    - sqlite-devel
    - libyaml
    - libyaml-devel
    - tcl-devel
    - db4-devel
    - libffi-devel
    - libxml2
    - libxml2-devel
    - libxslt
    - libxslt-devel
    - ImageMagick
    - ImageMagick-devel
  tags:
    - yum_install
