---
- name: git clone dotfiles repository
  become: no
  git:
    repo=git@github.com:shifumin/dotfiles.git
    dest=/home/{{ user }}/dotfiles
    accept_hostkey=yes

- name: put a symbolic link to dotfiles
  become: no
  shell: >
    {{ item }}
    chdir=/home/{{ user }}/dotfiles
  with_items:
    - ./setup.sh
  ignore_errors: True
